

baseURL = "https://navada-hugo.netlify.app/"
languageCode = "en-us"
title = "Navada"
theme = "navada"
paginate=6
googleAnalytics = ""
# Code Highlight
pygmentsstyle = "Abyss"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
description = "Navada is a color UI theme for blogs"
author = "Chaitanya Chaturvedi"
authorImage = "https://img.icons8.com/emoji/96/000000/boy-emoji.png"
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true    
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/blog"
[[menu.main]]
name = "Categories"
url = "/categories"
[[menu.main]]
name = "Contact"
url = "/contact"
[[menu.footer]]
name = "About"
url = "/about"
[[menu.footer]]
name = "Privacy Policy"
url = "/privacy"
[[menu.social]]
name = "BuyMeACoffee"
url = "https://www.buymeacoffee.com/chaitanya4vedi"
pre = "<i class='fas fa-coffee'></i>"
[[menu.social]]
name = "GitHub"
url = "https://github.com/chaitanya4vedi"
pre = "<i class='fab fa-github'></i>"
[[menu.social]]
name = "Twitter"
url = "https://twitter.com/chaitanya4vedi"
pre = "<i class='fab fa-twitter'></i>"
[related]
threshold = 0
includeNewer = true
toLower = false
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "date"
weight = 10
[module]
  [module.hugoVersion]
    extended = true
    min = "0.68.3"
    max = "0.84.2"

